name: "IRC"
on:
  push:
  pull_request:
  issue_comment:
    types: [created, edited]

jobs:
  irc:
    runs-on: ubuntu-latest
    steps:
      - name: irc push
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'push'
        with:
          channel: "#disco-lang"
          nickname: disco-bot
          message: |
            ${{ github.actor }} pushed to ${{ github.event.ref }} ${{ github.event.compare }}
            ${{ join(github.event.commits.*.message, '\n') }}
          notice: true
      - name: irc pull request
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'pull_request'
        with:
          channel: "#disco-lang"
          nickname: disco-bot
          message: |
            ${{ github.actor }} opened PR ${{ github.event.html_url }}
          notice: true
