name: "Push Notification"
on: [push, pull_request, create]

jobs:
  irc:
    runs-on: ubuntu-latest
    steps:
      - name: irc push
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'push'
        with:
          channel: "#disco-lang"
          nickname: disco-bot
          message: |
            \x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}
            ${{ github.actor }} pushed to \x0306${{ github.event.ref }}\x03 ${{ github.event.compare }}
            ${{ join(github.event.commits.*.message, '\n') }}
          notice: true
      - name: irc pull request
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'pull_request'
        with:
          channel: "#disco-lang"
          nickname: disco-bot
          message: |
            ${{ github.actor }} opened PR ${{ github.event.html_url }}
          notice: true
